# access-token:
#   private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
#   public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

# refresh-token:
#   private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
#   public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

# spring:
#   application:
#     name: PafBackend
#   profiles:
#     active: dev
#   data:
#     mongodb:
#       uri: mongodb+srv://rajapakshahimash:yA8qmx1EDI4imPrG@cluster0.8elegcm.mongodb.net/
#       database: ${MONGODB_DB}

#   security:
#     oauth2:
#       client:
#         registration:
#             google:
#             client-id: 125855925323-d54jdjburtgnqb1hebpd6otf5tmp1l4o.apps.googleusercontent.com
#             client-secret: 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
#             scope: profile, email
#         provider:
#           google:
#             authorization-uri: https://accounts.google.com/o/oauth2/auth
#             token-uri: https://oauth2.googleapis.com/token
#             user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#             user-name-attribute: email

# logging:
#   level:
#     org.springframework.security: DEBUG

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

spring:
  application:
    name: PafBackend

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb+srv://rajapakshahimash:yA8qmx1EDI4imPrG@cluster0.8elegcm.mongodb.net/
      database: ${MONGODB_DB}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 125855925323-d54jdjburtgnqb1hebpd6otf5tmp1l4o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
            
logging:
  level:
    org.springframework.security: DEBUG
